from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from . import views
from . import views_caratulas
from . import views_migrar  # TEMPORAL - ELIMINAR DESPUÉS

app_name = 'inmobiliaria'

urlpatterns = [
    # 🚨 TEMPORAL - MIGRACIÓN HEROKU → RAILWAY (ELIMINAR DESPUÉS)
    path('migrar-desde-heroku-SECRETO123/', views_migrar.migrar_desde_heroku, name='migrar_heroku'),
    path('api/ejecutar-migracion/', views_migrar.ejecutar_migracion_api, name='ejecutar_migracion'),
    path('api/resetear-password-temp/', views_migrar.resetear_password_temp, name='resetear_password_temp'),
    path('api/debug-usuarios/', views_migrar.debug_usuarios, name='debug_usuarios'),
    
    # Auth URLs
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='inmobiliaria:login'), name='logout'),
    path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),

    # Redirect root URL to register
    path('', RedirectView.as_view(url='/register/', permanent=False), name='index'),

    # Vendedor URLs
    path('vendedores/', views.vendedores, name='vendedores'),
    path('vendedores/<int:vendedor_id>/', views.vendedor_detalle, name='vendedor_detalle'),
    path('vendedores/nuevo/', views.vendedor_nuevo, name='vendedor_nuevo'),
    path('vendedores/<int:vendedor_id>/editar/', views.vendedor_editar, name='vendedor_editar'),
    path('vendedores/<int:vendedor_id>/eliminar/', views.vendedor_eliminar, name='vendedor_eliminar'),
    path('historial-reservas-vendedor/<int:vendedor_id>/', views.historial_reservas_vendedor, name='historial_reservas_vendedor'),
    # Inquilino URLs
    path('inquilinos/', views.inquilinos, name='inquilinos'),
    path('inquilinos/<int:inquilino_id>/', views.inquilino_detalle, name='inquilino_detalle'),
    path('inquilinos/nuevo/', views.inquilino_nuevo, name='inquilino_nuevo'),
    path('inquilinos/<int:inquilino_id>/editar/', views.inquilino_editar, name='inquilino_editar'),
    path('inquilinos/<int:inquilino_id>/eliminar/', views.inquilino_eliminar, name='inquilino_eliminar'),
    path('historial-reservas-inquilino/<int:inquilino_id>/', views.historial_reservas_inquilino, name='historial_reservas_inquilino'),
    path('inquilinos/<int:inquilino_id>/historial/', views.historial_reservas_inquilino, name='inquilino_historial_alias'),
    # Propietario URLs
    path('propietarios/', views.propietarios, name='propietarios'),
    path('propietarios/<int:propietario_id>/', views.propietario_detalle, name='propietario_detalle'),
    path('propietarios/nuevo/', views.propietario_nuevo, name='propietario_nuevo'),
    path('propietarios/<int:propietario_id>/editar/', views.propietario_editar, name='propietario_editar'),
    path('propietarios/<int:propietario_id>/eliminar/', views.propietario_eliminar, name='propietario_eliminar'),
    path('crear-propietario/', views.crear_propietario_ajax, name='crear_propietario_ajax'),
    path('propiedad/<int:propiedad_id>/precios/', views.gestionar_precios, name='gestionar_precios'),
    path('propietario/<int:propietario_id>/propiedades/', views.propiedades_propietario, name='propiedades_propietario'),
    # Propiedad URLs
    path('propiedades/', views.propiedades, name='propiedades'),
    path('propiedades/<int:propiedad_id>/', views.propiedad_detalle, name='propiedad_detalle'),
    path('propiedades/nuevo/', views.propiedad_nuevo, name='propiedad_nuevo'),
    path('propiedades/<str:propiedad_id>/editar/', views.propiedad_editar, name='propiedad_editar'),
    path('propiedades/<int:propiedad_id>/cambiar-sucursal/', views.propiedad_cambiar_sucursal, name='propiedad_cambiar_sucursal'),
    path('propiedades/<int:propiedad_id>/eliminar/', views.propiedad_eliminar, name='propiedad_eliminar'),
    path('propiedades-eliminadas/', views.propiedades_eliminadas, name='propiedades_eliminadas'),
    path('propiedades/<int:propiedad_id>/recuperar/', views.propiedad_recuperar, name='propiedad_recuperar'),
    path('propiedades/nuevo/', views.propiedad_nuevo, name='propiedad_nuevo'),
    path('propiedad/<int:propiedad_id>/crear-disponibilidad/', views.crear_disponibilidad, name='crear_disponibilidad'),
 
    path('propietario/nuevo/ajax/', views.propietario_nuevo_ajax, name='propietario_nuevo_ajax'),
    path('buscar-clientes/', views.buscar_clientes, name='buscar_clientes'),
    path('crear-inquilino-ajax/', views.crear_inquilino_ajax, name='crear_inquilino_ajax'),
    path('crear-concepto-ajax/', views.crear_concepto_ajax, name='crear_concepto_ajax'),
    path('procesar-movimiento-reserva/', views.procesar_movimiento_reserva, name='procesar_movimiento_reserva'),
    path('test-json/', views.test_json_response, name='test_json_response'),
    path('api/propiedad/<int:propiedad_id>/', views.api_propiedad_detalle, name='api_propiedad_detalle'),
    path('recibo-movimiento/<int:movimiento_id>/', views.ver_recibo_movimiento, name='ver_recibo_movimiento'),
    path('disponibilidad-masiva/', views.agregar_disponibilidad_masiva, name='agregar_disponibilidad_masiva'),
    path('disponibilidad/<int:disponibilidad_id>/eliminar/', views.eliminar_disponibilidad, name='eliminar_disponibilidad'),
    path('disponibilidad/<int:disponibilidad_id>/editar/', views.editar_disponibilidad, name='editar_disponibilidad'),
    path('propiedades/<int:propiedad_id>/corregir-superposiciones/', views.corregir_superposiciones_disponibilidades, name='corregir_superposiciones_disponibilidades'),
    path('sucursal/<int:sucursal_id>/configurar-numeracion-recibos/', views.configurar_numeracion_recibos, name='configurar_numeracion_recibos'),
    path('propiedad/<int:propiedad_id>/historial-disponibilidad/', views.ver_historial_disponibilidad, name='historial_disponibilidad'),
    path('limpiar-historial-disponibilidad/', views.limpiar_historial_disponibilidad, name='limpiar_historial_disponibilidad'),
    path('editar-historial-disponibilidad/', views.editar_historial_disponibilidad, name='editar_historial_disponibilidad'),
    path('propiedades/<int:propiedad_id>/reconstruir-historial/', views.reconstruir_historial_propiedad_ajax, name='reconstruir_historial_propiedad_ajax'),
    path('propiedades/<int:propiedad_id>/actualizar-historial-invierno/', views.actualizar_historial_invierno_propiedad, name='actualizar_historial_invierno_propiedad'),
    path('editar-historial-reserva/', views.editar_historial_reserva, name='editar_historial_reserva'),
    path('limpieza-brutal/', views.limpieza_brutal, name='limpieza_brutal'),
    path('propiedades/buscar-por-fechas/', views.buscar_propiedades_por_fechas, name='buscar_propiedades_por_fechas'),
    # Estudiantes
    path('estudiantes/', views.estudiantes, name='estudiantes'),
    path('estudiantes/disponibilidad-masiva/', views.estudiantes_disponibilidad_masiva, name='estudiantes_disponibilidad_masiva'),
    path('estudiantes/buscar/', views.buscar_propiedades_estudiantes, name='buscar_propiedades_estudiantes'),
    path('utilidades/diagrama-db/', views.ver_diagrama_db, name='ver_diagrama_db'),

    # Búsqueda URLs
    path('buscar-propiedad/', views.buscar_propiedad, name='buscar_propiedad'),
    path('buscar-vendedor/', views.buscar_vendedor, name='buscar_vendedor'),
    path('buscar-vendedores/', views.buscar_vendedores, name='buscar_vendedores'),
    path('buscar-movimiento/', views.buscar_movimiento, name='buscar_movimiento'),
    path('buscar-liquidacion-caja/', views.buscar_liquidacion_caja, name='buscar_liquidacion_caja'),
    path('buscar-movimientos/', views.buscar_movimientos, name='buscar_movimientos'),

    # Reserva URLs
    path('reservas/', views.reservas, name='reservas'),
    path('reservas/eliminadas/', views.reservas_eliminadas, name='reservas_eliminadas'),
    path('operaciones/', views.operaciones, name='operaciones'),
    path('caratulas/', views_caratulas.lista_caratulas, name='lista_caratulas'),
    path('caratulas/reserva/<int:reserva_id>/imprimir/', views_caratulas.imprimir_caratula_reserva, name='imprimir_caratula_reserva'),
    path('caratulas/contrato/<int:contrato_id>/imprimir/', views_caratulas.imprimir_caratula_contrato, name='imprimir_caratula_contrato'),
    path('caratulas/reserva/<int:reserva_id>/', views_caratulas.caratula_reserva, name='caratula_reserva'),
    path('caratulas/contrato/<int:contrato_id>/', views_caratulas.caratula_contrato, name='caratula_contrato'),
    path('reservas/nuevo/', views.buscar_propiedades, name='buscar_propiedades'),
    path('reservas/crear/', views.crear_reserva, name='crear_reserva'),
    path('reservas/<int:reserva_id>/', views.reserva_detalle, name='reserva_detalle'),
    path('confirmar_reserva/', views.confirmar_reserva, name='confirmar_reserva'),
    path('reserva_exitosa/<int:reserva_id>/', views.reserva_exitosa, name='reserva_exitosa'),
    path('reservas/<int:reserva_id>/terminar/', views.terminar_reserva, name='finalizar_reserva'),
    path('reservas/<int:reserva_id>/finalizar-nueva/', views.finalizar_reserva_nueva, name='finalizar_reserva_nueva'),
    path('reservas/<int:reserva_id>/actualizar-precio/', views.actualizar_precio_reserva, name='actualizar_precio_reserva'),
    path('reservas/<int:reserva_id>/editar/', views.reserva_editar, name='reserva_editar'),
    path('reservas/<int:reserva_id>/agregar-pago/', views.agregar_pago, name='agregar_pago'),
    path('reservas/<int:reserva_id>/agregar-deposito/', views.agregar_deposito, name='agregar_deposito'),
    path('buscar-propietarios/', views.buscar_propietarios, name='buscar_propietarios'),
    path('buscar-inquilinos/', views.buscar_inquilinos, name='buscar_inquilinos'),
    path('reserva/eliminar/<int:reserva_id>/', views.reserva_eliminar, name='reserva_eliminar'),
    path('autenticacion-vendedor/', views.autenticacion_vendedor, name='autenticacion_vendedor'),
    path('autenticar-seguridad/', views.autenticar_seguridad, name='autenticar_seguridad'),
    path('obtener_precios_propiedad/', views.obtener_precios_propiedad, name='obtener_precios_propiedad'),
    path('obtener_vendedor/<int:vendedor_id>/', views.obtener_vendedor, name='obtener_vendedor'),
    path('obtener-inquilino/<int:inquilino_id>/', views.obtener_inquilino, name='obtener_inquilino'),
    path('crear-sucursal/', views.crear_sucursal, name='crear_sucursal'),
    path('actualizar-orden-imagenes/', views.actualizar_orden_imagenes, name='actualizar_orden_imagenes'),
    path('eliminar-imagen/', views.eliminar_imagen, name='eliminar_imagen'),
    path('ver-recibo/<int:reserva_id>/', views.ver_recibo, name='ver_recibo'),
    path('reserva/<int:reserva_id>/recibo/', views.ver_recibo, name='ver_recibo'),
    path('ver-recibo-pdf/<int:reserva_id>/', views.ver_recibo_pdf, name='ver_recibo_pdf'),
    path('recibo-movimiento-pdf/<int:movimiento_id>/', views.ver_recibo_movimiento_pdf, name='ver_recibo_movimiento_pdf'),
    path('recibo-publico/<int:reserva_id>/<str:token>/', views.ver_recibo_publico, name='ver_recibo_publico'),
    path('recibo-movimiento-publico/<int:movimiento_id>/<str:token>/', views.ver_recibo_movimiento_publico, name='ver_recibo_movimiento_publico'),
    path('generar-enlace-publico/', views.generar_enlace_publico, name='generar_enlace_publico'),
    path('reservas/<int:reserva_id>/detalles-operacion/', views.detalles_operacion_reserva, name='detalles_operacion_reserva'),
    path('reservas/<int:reserva_id>/info/', views.obtener_info_reserva, name='obtener_info_reserva'),
   
    path('password_reset/done/', 
         auth_views.PasswordResetDoneView.as_view(
             template_name='inmobiliaria/autenticacion/password_reset_done.html'
         ), 
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='inmobiliaria/autenticacion/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='inmobiliaria/autenticacion/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('recuperar-password/', views.enviar_recuperacion, name='recuperar_password'),
    path('cambiar-password/', views.cambiar_password, name='cambiar_password'),
    path('reserva/<int:reserva_id>/confirmar-pago/', views.confirmar_pago, name='confirmar_pago'),
    path('reserva/<int:reserva_id>/agregar-pago/', views.agregar_pago, name='agregar_pago'),
    path('pago/<int:pago_id>/eliminar/', views.eliminar_pago, name='eliminar_pago'),
    path('reserva/<int:reserva_id>/agregar-deposito/', views.agregar_deposito, name='agregar_deposito'),
    path('propiedades/<str:propiedad_id>/editar-venta/', 
         views.editar_info_venta, 
         name='editar_info_venta'),
    path('propiedades/<int:propiedad_id>/editar-meses/', views.editar_info_meses, name='editar_info_meses'),
    path('ventas/', views.ventas, name='ventas'),
    path('alquileres-24-meses/', views.alquileres_24_meses, name='alquileres_24_meses'),
    path('alquileres-invierno/', views.alquileres_invierno, name='alquileres_invierno'),
    path('alquileres-invierno/disponibilidad-masiva/', views.invierno_disponibilidad_masiva, name='invierno_disponibilidad_masiva'),
    path('dashboard/ventas/', views.ventas, name='dashboard_ventas'),
    path('propiedad/<int:propiedad_id>/iniciar-compra/', views.iniciar_compra, name='iniciar_compra'),
    path('caja/', views.gestionar_caja, name='gestionar_caja'),
    path('caja/abrir/', views.abrir_caja, name='abrir_caja'),
    path('caja/<int:numero>/cerrar/', views.cerrar_caja, name='cerrar_caja'),
    path('caja/movimiento/nuevo/', views.nuevo_movimiento, name='nuevo_movimiento'),
    path('caja/', views.caja, name='caja'),
    path('caja/nuevo/', views.nuevo_movimiento, name='nuevo_movimiento'),
    path('caja/eliminar/<int:movimiento_id>/', views.eliminar_movimiento, name='eliminar_movimiento'),
    path('cajas/', views.lista_cajas, name='lista_cajas'),
    path('cajas/abrir/', views.abrir_caja, name='abrir_caja'),
    path('cajas/<int:numero>/', views.detalle_caja, name='detalle_caja'),
    path('cajas/<int:numero_caja>/movimiento/', views.nuevo_movimiento, name='nuevo_movimiento'),
    path('cajas/<int:numero_caja>/cerrar/', views.cerrar_caja, name='cerrar_caja'),
    path('caja/nuevo-registro/', views.nuevo_registro, name='nuevo_registro'),
    path('caja/nuevo-concepto/', views.nuevo_concepto, name='nuevo_concepto'),
    path('caja/buscar-cuentas/', views.buscar_cuentas, name='buscar_cuentas'),
    path('caja/crear-concepto/', views.crear_concepto, name='crear_concepto'),
    path('crear-propiedad/', views.crear_propiedad, name='crear_propiedad'),
    path('api/simple-select2/', views.simple_select2, name='simple_select2'),
    path('caja/crear-cuenta/', views.crear_cuenta, name='crear_cuenta'),
    path('buscar/propietarios/', views.buscar_propietarios, name='buscar_propietarios'),
    path('buscar/operacion/', views.buscar_operacion, name='buscar_operacion'),
    path('buscar/productores/', views.buscar_productores, name='buscar_productores'),
    path('propietario_cuentas/', views.propietario_cuentas, name='propietario_cuentas'),
    path('guardar_movimiento/', views.guardar_movimiento, name='guardar_movimiento'),
    path(
        "propietarios/buscar/",
        views.buscar_propietarios,
        name="buscar_propietarios",
    ),
    path("propiedades/nuevo/",               views.propiedad_nuevo,       name="propiedad_nuevo"),
    path("propiedades/<str:propiedad_id>/editar/",
         views.propiedad_editar,             name="propiedad_editar"),
    # Rutas de imágenes
    path('imagen/<int:imagen_id>/eliminar/', views.imagen_eliminar, name='imagen_eliminar'),
    path('propiedad/<int:propiedad_id>/eliminar-todas-imagenes/', views.eliminar_todas_imagenes, name='eliminar_todas_imagenes'),
    path('propiedades/<int:propiedad_id>/reordenar-imagenes/', views.reordenar_imagenes, name='reordenar_imagenes'),
    path('obtener-caracteristicas-propiedad/', views.obtener_caracteristicas_propiedad, name='obtener_caracteristicas_propiedad'),
    # Sucursal URLs
    path('sucursal/', views.sucursales, name='sucursales'),
    path('sucursal/<int:sucursal_id>/', views.sucursal_detalle, name='sucursal_detalle'),
    path('sucursal/<int:sucursal_id>/editar/', views.editar_sucursal, name='editar_sucursal'),
    path('obtener-fotos-propiedad/<int:propiedad_id>/', views.obtener_fotos_propiedad, name='obtener_fotos_propiedad'),
    path('obtener-precios-propiedad/<int:propiedad_id>/', views.obtener_precios_propiedad, name='obtener_precios_propiedad'),
    path('guardar-precios-propiedad/', views.guardar_precios_propiedad, name='guardar_precios_propiedad'),
    path('guardar-precio-individual/', views.guardar_precio_individual, name='guardar_precio_individual'),
    
    # Rutas de imágenes
    path('imagen/<int:imagen_id>/eliminar/', views.imagen_eliminar, name='imagen_eliminar'),
    path('propiedad/<int:propiedad_id>/eliminar-todas-imagenes/', views.eliminar_todas_imagenes, name='eliminar_todas_imagenes'),
    
    # Caja URLs
    path('cajas/', views.lista_cajas, name='lista_cajas'),
    path('cajas/<int:numero_caja>/movimiento/', views.nuevo_movimiento, name='nuevo_movimiento'),
    path('cajas/<int:numero_caja>/cerrar/', views.cerrar_caja, name='cerrar_caja'),
    path('cajas/<int:numero>/detalle/', views.detalle_caja, name='detalle_caja'),
    path('cajas/<int:numero>/resumen-imprimir/', views.imprimir_resumen_caja, name='imprimir_resumen_caja'),
    path('caja/', views.caja, name='caja'),
    path('caja/nuevo-movimiento/', views.nuevo_movimiento, name='nuevo_movimiento_sin_caja'),
    path('caja/dashboard/', views.dashboard_caja, name='dashboard_caja'),
    path('caja/reportes/', views.reportes_caja, name='reportes_caja'),
    path('reportes/entradas/', views.listado_entradas, name='listado_entradas'),
    path('reportes/salidas/', views.listado_salidas, name='listado_salidas'),
    path('caja/arqueo/', views.arqueo_caja, name='arqueo_caja'),
    path('caja/historial/', views.historial_caja, name='historial_caja'),
    path('caja/movimientos/', views.todos_movimientos_caja, name='todos_movimientos_caja'),
    path('caja/conceptos/buscar/', views.buscar_conceptos, name='buscar_conceptos'),
    path('caja/conceptos/crear/', views.crear_concepto, name='crear_concepto'),
    path('caja/propiedad/buscar/', views.buscar_propiedad, name='buscar_propiedad'),
    path('caja/propiedades/buscar/', views.buscar_propiedades_caja, name='buscar_propiedades_caja'),
    path('caja/propiedad/historial/', views.historial_propiedad_caja, name='historial_propiedad_caja'),
    path(
        'administracion/propiedades/operaciones/',
        views.administracion_propiedades_operaciones,
        name='administracion_propiedades_operaciones',
    ),
    path('caja/obtener-actual/', views.obtener_caja_actual, name='obtener_caja_actual'),
    
    # ============================
    # URLs PARA CONTRATOS 24 MESES
    # ============================
    
    # APIs
    path('api/inquilino/<int:inquilino_id>/', views.api_inquilino_detalle, name='api_inquilino_detalle'),
    path('api/vendedor/<int:vendedor_id>/', views.api_vendedor_detalle, name='api_vendedor_detalle'),
    
    # Contratos
    path('contratos/crear/', views.crear_contrato_alquiler, name='crear_contrato_alquiler'),
    path('contratos/', views.lista_contratos, name='lista_contratos'),
    path('contratos/rescindir-duplicados/', views.rescindir_contratos_duplicados, name='rescindir_contratos_duplicados'),
    path('contratos/actualizar-historiales-invierno/', views.actualizar_historiales_invierno, name='actualizar_historiales_invierno'),
    path('contratos/<int:contrato_id>/', views.detalle_contrato, name='detalle_contrato'),
    path('contratos/<int:contrato_id>/precios-bloques/', views.actualizar_precios_bloques_contrato, name='actualizar_precios_bloques_contrato'),
    path('contratos/<int:contrato_id>/moneda-cuotas/', views.actualizar_moneda_cuotas_contrato, name='actualizar_moneda_cuotas_contrato'),
    path('contratos/<int:contrato_id>/activar-trimestres/', views.activar_precios_trimestres_contrato, name='activar_precios_trimestres_contrato'),
    path('contratos/<int:contrato_id>/operacion/', views.crear_operacion_contrato, name='crear_operacion_contrato'),
    path(
        'contratos/<int:contrato_id>/cargos-iniciales/',
        views.completar_cargos_iniciales_contrato,
        name='completar_cargos_iniciales_contrato',
    ),
    path(
        'contratos/<int:contrato_id>/cargos-iniciales/procesar/',
        views.procesar_cargos_iniciales_contrato,
        name='procesar_cargos_iniciales_contrato',
    ),
    path('contratos/<int:contrato_id>/procesar-operacion/', views.procesar_operacion_contrato, name='procesar_operacion_contrato'),
    path('contratos/<int:contrato_id>/cuotas/', views.ver_cuotas_contrato, name='ver_cuotas_contrato'),
    path(
        'contratos/<int:contrato_id>/cuotas/agregar/',
        views.agregar_cuota_contrato,
        name='agregar_cuota_contrato',
    ),
    path(
        'contratos/<int:contrato_id>/cuotas/eliminar-ultima/',
        views.eliminar_ultima_cuota_contrato,
        name='eliminar_ultima_cuota_contrato',
    ),
    path(
        'contratos/<int:contrato_id>/cuotas/<int:cuota_id>/eliminar-super/',
        views.eliminar_cuota_contrato_super_admin,
        name='eliminar_cuota_contrato_super_admin',
    ),
    path(
        'contratos/<int:contrato_id>/cuotas/<int:cuota_id>/anular-pago-super/',
        views.anular_pago_cuota_contrato_super_admin,
        name='anular_pago_cuota_contrato_super_admin',
    ),
    path(
        'contratos/<int:contrato_id>/cuotas/reiniciar-plan-super/',
        views.reiniciar_plan_cuotas_contrato_super_admin,
        name='reiniciar_plan_cuotas_contrato_super_admin',
    ),
    path(
        'contratos/<int:contrato_id>/recalcular-montos-cuotas/',
        views.recalcular_cuotas_montos_desde_contrato,
        name='recalcular_cuotas_montos_desde_contrato',
    ),
    path('api/cuota/<int:cuota_id>/', views.api_cuota_detalle, name='api_cuota_detalle'),
    path('contratos/cuota/<int:cuota_id>/pagar/', views.pagar_cuota, name='pagar_cuota'),
    path(
        'contratos/cuota/<int:cuota_id>/recibo/',
        views.ver_recibo_cuota_contrato,
        name='ver_recibo_cuota_contrato',
    ),
    path(
        'contratos/cuota/<int:cuota_id>/pago-operacion/',
        views.crear_pago_cuota_operacion,
        name='crear_pago_cuota_operacion',
    ),
    path(
        'contratos/cuota/<int:cuota_id>/pago-operacion/procesar/',
        views.procesar_pago_cuota_operacion,
        name='procesar_pago_cuota_operacion',
    ),
    path('contratos/<int:contrato_id>/cancelar/', views.cancelar_contrato, name='cancelar_contrato'),
    path('contratos/<int:contrato_id>/recibo/', views.recibo_contrato_24, name='recibo_contrato_24'),
    path('contratos/<int:contrato_id>/comodato-invierno/', views.ver_comodato_invierno, name='ver_comodato_invierno'),
    path('contratos/<int:contrato_id>/contrato-estudiante/', views.ver_contrato_estudiante, name='ver_contrato_estudiante'),
    path('propiedades/<int:propiedad_id>/reactivar-24-meses/', views.reactivar_propiedad_24_meses, name='reactivar_propiedad_24_meses'),
    path('propiedades/<int:propiedad_id>/desactivar-24-meses/', views.desactivar_propiedad_24_meses, name='desactivar_propiedad_24_meses'),
    path('propiedades/<int:propiedad_id>/meses-info/', views.obtener_meses_info_ajax, name='obtener_meses_info_ajax'),
    path('actualizar-meses-ajax/', views.actualizar_meses_ajax, name='actualizar_meses_ajax'),
    path('propiedades/<int:propiedad_id>/editar-invierno/', views.editar_info_invierno, name='editar_info_invierno'),
    path('propiedades/<int:propiedad_id>/invierno-info/', views.obtener_invierno_info_ajax, name='obtener_invierno_info_ajax'),
    path('actualizar-invierno-ajax/', views.actualizar_invierno_ajax, name='actualizar_invierno_ajax'),
    path('propiedades/<int:propiedad_id>/reactivar-invierno/', views.reactivar_propiedad_invierno, name='reactivar_propiedad_invierno'),
    path('propiedades/<int:propiedad_id>/desactivar-invierno/', views.desactivar_propiedad_invierno, name='desactivar_propiedad_invierno'),
    
    # Gestión de Conceptos
    path('conceptos/', views.gestionar_conceptos, name='gestionar_conceptos'),
    
    # Gestión de Cuentas Bancarias
    path('cuentas-bancarias/', views.gestionar_cuentas_bancarias, name='gestionar_cuentas_bancarias'),
    path('cuentas-bancarias/crear/', views.crear_cuenta_bancaria, name='crear_cuenta_bancaria'),
    path(
        'cuentas-bancarias/<int:cuenta_id>/movimientos/',
        views.reporte_movimientos_cuenta_bancaria,
        name='reporte_movimientos_cuenta_bancaria',
    ),
    path('cuentas-bancarias/<int:cuenta_id>/editar/', views.editar_cuenta_bancaria, name='editar_cuenta_bancaria'),
    path('cuentas-bancarias/<int:cuenta_id>/eliminar/', views.eliminar_cuenta_bancaria, name='eliminar_cuenta_bancaria'),
    path('cuentas-bancarias/<int:cuenta_id>/toggle/', views.toggle_cuenta_bancaria, name='toggle_cuenta_bancaria'),
    
    # ✅ URLs para Comisiones de Vendedores (Solo Admins)
    path('comisiones/', views.dashboard_comisiones, name='dashboard_comisiones'),
    path('vendedores/<int:vendedor_id>/comisiones/', views.historial_comisiones_vendedor, name='historial_comisiones_vendedor'),
    path(
        'vendedores/<int:vendedor_id>/comisiones/mes-pagado/',
        views.toggle_mes_comision_pagado,
        name='toggle_mes_comision_pagado',
    ),
    path('comisiones/<int:comision_id>/', views.detalle_comision, name='detalle_comision'),
    path('vendedores/<int:vendedor_id>/comisiones/mes/<int:anio>/<int:mes>/', views.resumen_comisiones_mensual, name='resumen_comisiones_mensual'),
    
    # ✅ URLs para Vales de Vendedores
    path('vales/crear/', views.crear_vale, name='crear_vale'),
    path('vendedores/<int:vendedor_id>/vales/', views.lista_vales_vendedor, name='lista_vales_vendedor'),
    
    # ✅ URLs para Liquidaciones de Propietarios
    path('reportes/asegurado-liquidaciones/<int:disponibilidad_id>/', views.reporte_asegurado_liquidaciones, name='reporte_asegurado_liquidaciones_detalle'),
    path('reportes/asegurado-liquidaciones/', views.reporte_asegurado_liquidaciones, name='reporte_asegurado_liquidaciones'),
    path('liquidaciones/', views.lista_liquidaciones, name='lista_liquidaciones'),
    path('liquidaciones/crear/', views.crear_liquidacion, name='crear_liquidacion'),
    path('liquidaciones/crear/<int:reserva_id>/', views.crear_liquidacion, name='crear_liquidacion_reserva'),
    path(
        'liquidaciones/crear/contrato/<int:contrato_id>/',
        views.crear_liquidacion,
        name='crear_liquidacion_contrato',
    ),
    path('liquidaciones/<int:liquidacion_id>/eliminar/', views.eliminar_liquidacion, name='eliminar_liquidacion'),
    path('liquidaciones/<int:liquidacion_id>/', views.detalle_liquidacion, name='detalle_liquidacion'),
    path(
        'liquidaciones/<int:liquidacion_id>/imprimir-cobranzas/',
        views.imprimir_liquidacion_cobranzas,
        name='imprimir_liquidacion_cobranzas',
    ),
    path('liquidaciones/<int:liquidacion_id>/agregar-gasto/', views.agregar_gasto, name='agregar_gasto'),
    path(
        'liquidaciones/<int:liquidacion_id>/vincular-gasto-pendiente/',
        views.vincular_gasto_pendiente_liquidacion,
        name='vincular_gasto_pendiente_liquidacion',
    ),
    path('liquidaciones/gasto/<int:gasto_id>/aceptar-rechazar/', views.aceptar_rechazar_gasto, name='aceptar_rechazar_gasto'),
    path('liquidaciones/gasto/<int:gasto_id>/eliminar/', views.eliminar_gasto_liquidacion, name='eliminar_gasto_liquidacion'),
    path('liquidaciones/<int:liquidacion_id>/confirmar/', views.confirmar_liquidacion, name='confirmar_liquidacion'),
    path('liquidaciones/<int:liquidacion_id>/marcar-oficina/', views.marcar_liquidacion_oficina, name='marcar_liquidacion_oficina'),
    path('liquidaciones/<int:liquidacion_id>/procesar/', views.procesar_liquidacion, name='procesar_liquidacion'),
    path('liquidaciones/buscar-operacion/', views.buscar_operacion_liquidacion, name='buscar_operacion_liquidacion'),
    path('liquidaciones/propiedad/<int:propiedad_id>/operaciones-pendientes/', views.obtener_operaciones_pendientes, name='obtener_operaciones_pendientes'),
    path(
        'liquidaciones/propietario/<int:propietario_id>/operaciones-pendientes/',
        views.obtener_operaciones_pendientes_propietario,
        name='obtener_operaciones_pendientes_propietario',
    ),
    path('liquidaciones/gasto-pendiente/crear/', views.crear_gasto_pendiente, name='crear_gasto_pendiente'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
