# Generated by Django 4.2.7 on 2024-11-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0001_initial'),
    ]

    # operations = [
    #     migrations.RunSQL(
    #         sql="ALTER TABLE inmobiliaria_vendedor DROP KEY inmobiliaria_vendedor_dni_key;",
    #         reverse_sql="ALTER TABLE inmobiliaria_vendedor ADD KEY inmobiliaria_vendedor_dni_key (dni);"
    #     ),
    # ]