# Generated by Django 4.2.7 on 2025-04-22 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado')], default='confirmado', max_length=20),
        ),
        migrations.AlterField(
            model_name='caja',
            name='fecha_apertura',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
