# Generated by Django 4.2.7 on 2024-09-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='departamento',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
