# Generated by Django 4.2.7 on 2024-11-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0002_auto_20241122_1211'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vendedor',
            name='unique_dni',
        ),
    ]
