# Generated by Django 5.1.3 on 2024-12-03 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0002_auto_20241122_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquilino',
            name='cuit',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='CUIT debe tener 11 dígitos', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='cuit',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='CUIT debe tener 11 dígitos', regex='^\\d{11}$')]),
        ),
    ]
