# Generated by Django 4.2.7 on 2025-04-22 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0002_movimientocaja_estado_alter_caja_fecha_apertura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BancoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='caja',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='comprobante',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='usuario',
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='a_descontar',
            field=models.CharField(blank=True, choices=[('propietario', 'Propietario'), ('inquilino', 'Inquilino'), ('oficina', 'Oficina')], max_length=20),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='con_iva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='fecha_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='fecha_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='monto_cheque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='monto_deposito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='monto_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='monto_qr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='monto_tarjeta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='numero_liquidacion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='pasa_liquidaciones',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inmobiliaria.propiedad'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.sucursal'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='tipo_comprobante',
            field=models.CharField(choices=[('RC', 'Recibo'), ('LQ', 'Liquidación'), ('GS', 'Gasto'), ('OT', 'Otro')], default='RC', max_length=2),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='concepto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo',
            field=models.CharField(choices=[('IN', 'Ingreso'), ('EG', 'Egreso')], default='IN', max_length=2),
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interno_caja', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('IN', 'Ingreso'), ('EG', 'Egreso')], default='IN', max_length=2)),
                ('tipo_comprobante', models.CharField(choices=[('RC', 'Recibo'), ('LQ', 'Liquidación'), ('GS', 'Gasto'), ('OT', 'Otro')], max_length=2)),
                ('fecha_comprobante', models.DateField()),
                ('liquidacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cheques', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('tipo_descuento', models.CharField(blank=True, choices=[('PR', 'Propietario'), ('IN', 'Inquilino'), ('OF', 'Oficina')], max_length=2, null=True)),
                ('con_iva', models.BooleanField(default=False)),
                ('pasa_liquidaciones', models.BooleanField(default=False)),
                ('concepto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inmobiliaria.concepto')),
                ('cuenta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inmobiliaria.cuenta')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('propiedad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inmobiliaria.propiedad')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.sucursal')),
            ],
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inmobiliaria.bancotarjeta'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inmobiliaria.cuenta'),
        ),
    ]
