# Generated by Django 4.2.7 on 2024-11-22 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0003_remove_vendedor_unique_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_sucursal', to='inmobiliaria.sucursal'),
        ),
    ]
