# Generated by Django 4.2.7 on 2024-12-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0003_alter_inquilino_cuit_alter_propietario_cuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='llave',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Número de llave'),
        ),
    ]
