# Generated by Django 4.2.7 on 2025-04-23 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0004_alter_caja_fecha_apertura_alter_caja_saldo_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.caja'),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.sucursal'),
            preserve_default=False,
        ),
    ]
