# Generated by Django 4.2.7 on 2024-12-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0004_propiedad_llave'),
    ]

    operations = [
        migrations.AddField(
            model_name='precio',
            name='precio_dia_toma',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio dia: Toma'),
        ),
        migrations.AddField(
            model_name='precio',
            name='precio_toma',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Toma'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='ajuste_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ajuste (%)'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='precio_por_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por día'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio total'),
        ),
    ]
