# Generated by Django 4.2.7 on 2025-05-09 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0005_movimientocaja_caja_alter_movimientocaja_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialdisponibilidad',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_disponibilidad', to='inmobiliaria.reserva'),
        ),
    ]
