# Generated by Django 4.2.7 on 2024-12-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0005_precio_precio_dia_toma_precio_precio_toma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='deposito',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Depósito'),
        ),
    ]
