# Generated by Django 4.2.7 on 2025-05-22 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0006_historialdisponibilidad_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='numero_por_propietario',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagenpropiedad',
            name='orden',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='imagenpropiedad',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inmobiliaria.propiedad'),
        ),
    ]
