# Generated by Django 4.2.7 on 2025-05-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0007_propiedad_numero_por_propietario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='numero_por_propietario',
            field=models.PositiveIntegerField(),
        ),
    ]
