# Generated by Django 4.2.7 on 2024-12-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0007_alter_vendedor_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='password_temporal',
            field=models.BooleanField(default=False, help_text='Indica si el usuario debe cambiar su contraseña en el próximo inicio de sesión', verbose_name='Contraseña temporal'),
        ),
    ]
