# Generated by Django 4.2.7 on 2024-12-13 14:36

from django.db import migrations, models
import django.db.models.deletion

def cargar_conceptos_iniciales(apps, schema_editor):
    ConceptoPago = apps.get_model('inmobiliaria', 'ConceptoPago')
    conceptos = [
        {'codigo': 'SENA', 'nombre': 'Seña', 'descripcion': 'Pago inicial para reservar la propiedad'},
        {'codigo': 'SALDO', 'nombre': 'Saldo', 'descripcion': 'Pago del saldo restante'},
        {'codigo': 'DEP', 'nombre': 'Depósito', 'descripcion': 'Depósito de garantía'},
    ]
    for concepto in conceptos:
        ConceptoPago.objects.create(**concepto)

def revertir_conceptos(apps, schema_editor):
    ConceptoPago = apps.get_model('inmobiliaria', 'ConceptoPago')
    ConceptoPago.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0008_vendedor_password_temporal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Concepto de Pago',
                'verbose_name_plural': 'Conceptos de Pago',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=10, unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inmobiliaria.conceptopago')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inmobiliaria.reserva')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.RunPython(cargar_conceptos_iniciales, revertir_conceptos),
    ]