# Generated by Django 4.2.7 on 2024-12-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0009_load_conceptos_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='pago_total',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cuota_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_espera', 'En Espera'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='senia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
