# Generated by Django 4.2.7 on 2025-07-10 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0009_remove_llave_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventapropiedad',
            name='metros_cuadrados',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Metros cuadrados'),
        ),
        migrations.AlterField(
            model_name='imagenpropiedad',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imagenpropiedad',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_propiedad', to='inmobiliaria.propiedad'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='tipo_precio',
            field=models.CharField(choices=[('QUINCENA_1_DICIEMBRE', '1ra quincena Diciembre'), ('QUINCENA_2_DICIEMBRE', '2da quincena Diciembre'), ('QUINCENA_1_ENERO', '1ra quincena Enero'), ('QUINCENA_2_ENERO', '2da quincena Enero'), ('QUINCENA_1_FEBRERO', '1ra quincena Febrero'), ('QUINCENA_2_FEBRERO', '2da quincena Febrero'), ('QUINCENA_1_MARZO', '1ra quincena Marzo'), ('QUINCENA_2_MARZO', '2da quincena Marzo'), ('TEMPORADA_BAJA', 'Temporada baja'), ('VACACIONES_INVIERNO', 'Vacaciones Invierno'), ('FINDE_LARGO', 'Finde largo'), ('ESTUDIANTE', 'Estudiante')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='llave',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de llave'),
        ),
    ]
