# Generated by Django 4.2.7 on 2025-07-14 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0010_ventapropiedad_metros_cuadrados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenpropiedad',
            name='orden',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='imagenpropiedad',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inmobiliaria.propiedad'),
        ),
    ]
