# Generated by Django 4.2.7 on 2024-12-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0010_remove_reserva_pago_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='departamento',
            field=models.CharField(help_text='Número o letra del departamento', max_length=10, verbose_name='Departamento'),
        ),
    ]
