# Generated by Django 4.2.7 on 2025-07-18 13:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0011_update_imagen_propiedad_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concepto',
            options={'ordering': ['id'], 'verbose_name': 'Concepto', 'verbose_name_plural': 'Conceptos'},
        ),
        migrations.AddField(
            model_name='concepto',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='concepto',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='inmobiliaria.sucursal'),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='concepto',
            unique_together={('id', 'sucursal')},
        ),
    ]
