# Generated by Django 4.2.7 on 2024-12-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0011_alter_propiedad_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='piso',
            field=models.CharField(help_text='Número o descripción del piso (ej: PB, 1, 15, etc.)', max_length=10, verbose_name='Piso'),
        ),
    ]
