# Generated by Django 4.2.7 on 2025-07-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0012_alter_concepto_options_concepto_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientocaja',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='con_iva',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='monto_qr',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='pasa_liquidaciones',
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='destino_deposito',
            field=models.CharField(blank=True, choices=[('galicia', 'Galicia'), ('mp', 'Mercado Pago')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='a_descontar',
            field=models.CharField(choices=[('propietario', 'Propietario'), ('oficina', 'Oficina')], default='oficina', max_length=20),
        ),
    ]
