# Generated by Django 4.2.7 on 2025-07-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0013_remove_movimientocaja_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='destino_deposito',
            field=models.CharField(blank=True, choices=[('galicia', 'Galicia'), ('mp', 'Mercado Pago')], max_length=10, null=True, verbose_name='Destino de la Transferencia'),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='a_descontar',
            field=models.CharField(blank=True, choices=[('propietario', 'Propietario'), ('oficina', 'Oficina')], help_text='Solo necesario para egresos', max_length=20, null=True),
        ),
    ]
