# Generated by Django 4.2.7 on 2024-12-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0013_reserva_pago_total_alter_reserva_cuota_pendiente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='pago_total',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cuota_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='senia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
