# Generated by Django 4.2.7 on 2025-07-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0014_pago_destino_deposito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='numero_tarjeta',
        ),
        migrations.AlterField(
            model_name='pago',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('cheque', 'Cheque'), ('qr', 'QR')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('en_espera', 'En Espera'), ('confirmada', 'Confirmada'), ('confirmada_no_pagada', 'Confirmada No Pagada'), ('pagada', 'Pagada')], default='en_espera', max_length=20),
        ),
    ]
