# Generated by Django 4.2.7 on 2024-12-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0014_remove_reserva_pago_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={},
        ),
    ]
