# Generated by Django 4.2.7 on 2024-12-17 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0016_alter_pago_options_remove_reserva_deposito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('reservado', 'Reservado'), ('confirmado', 'Confirmado'), ('ocupado', 'Ocupado')], default='libre', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_disponibilidad', to='inmobiliaria.propiedad')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_disponibilidad', to='inmobiliaria.reserva')),
            ],
            options={
                'verbose_name': 'Historial de Disponibilidad',
                'verbose_name_plural': 'Historial de Disponibilidades',
                'ordering': ['fecha_inicio', 'fecha_fin'],
            },
        ),
    ]
