# Generated by Django 4.2.7 on 2024-12-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0018_add_default_conceptos_pagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='numero_tarjeta',
            field=models.CharField(blank=True, help_text='Últimos 4 dígitos de la tarjeta', max_length=16, null=True, verbose_name='Número de Tarjeta'),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_tarjeta',
            field=models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('american_express', 'American Express'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Tipo de Tarjeta'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('cheque', 'Cheque'), ('qr', 'QR')], max_length=20),
        ),
    ]
