# Generated by Django 4.2.7 on 2024-12-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0019_pago_numero_tarjeta_pago_tipo_tarjeta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='habilitar_23_meses',
            field=models.BooleanField(default=False, verbose_name='Habilitar para 24 Meses'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='habilitar_invierno',
            field=models.BooleanField(default=False, verbose_name='Habilitar para Invierno'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='habilitar_venta',
            field=models.BooleanField(default=False, verbose_name='Habilitar para Venta'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='precio_23_meses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio 23 Meses'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='precio_invierno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Invierno'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='historialdisponibilidad',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('reservado', 'Reservado'), ('ocupado', 'Ocupado')], default='libre', max_length=20),
        ),
    ]
