# Generated by Django 4.2.7 on 2024-12-23 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0021_alter_precio_tipo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenpropiedad',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_propiedad', to='inmobiliaria.propiedad'),
        ),
    ]
