# Generated manually to create basic Caja table

from django.db import migrations, models
import django.db.models.deletion


def create_caja_table(apps, schema_editor):
    """
    Crear tabla Caja compatible con MySQL y PostgreSQL
    """
    if schema_editor.connection.vendor == 'mysql':
        schema_editor.execute("""
            CREATE TABLE IF NOT EXISTS inmobiliaria_caja (
                id bigint NOT NULL AUTO_INCREMENT,
                numero int NOT NULL,
                sucursal_id bigint NOT NULL,
                fecha_apertura datetime(6) NOT NULL,
                fecha_cierre datetime(6) NULL,
                saldo_inicial decimal(10,2) NOT NULL,
                saldo_final decimal(10,2) NULL,
                estado varchar(20) NOT NULL DEFAULT 'abierta',
                usuario_apertura_id bigint NOT NULL,
                usuario_cierre_id bigint NULL,
                observaciones_apertura longtext NOT NULL DEFAULT '',
                observaciones_cierre longtext NOT NULL DEFAULT '',
                PRIMARY KEY (id),
                UNIQUE KEY inmobiliaria_caja_numero_sucursal_id_uniq (numero, sucursal_id)
            );
        """)
    elif schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("""
            CREATE TABLE IF NOT EXISTS inmobiliaria_caja (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                numero int NOT NULL,
                sucursal_id bigint NOT NULL,
                fecha_apertura timestamp NOT NULL,
                fecha_cierre timestamp NULL,
                saldo_inicial decimal(10,2) NOT NULL,
                saldo_final decimal(10,2) NULL,
                estado varchar(20) NOT NULL DEFAULT 'abierta',
                usuario_apertura_id bigint NOT NULL,
                usuario_cierre_id bigint NULL,
                observaciones_apertura text NOT NULL DEFAULT '',
                observaciones_cierre text NOT NULL DEFAULT '',
                PRIMARY KEY (id),
                CONSTRAINT inmobiliaria_caja_numero_sucursal_id_uniq UNIQUE (numero, sucursal_id)
            );
        """)


def drop_caja_table(apps, schema_editor):
    """
    Eliminar tabla Caja (reverse operation)
    """
    schema_editor.execute("DROP TABLE IF EXISTS inmobiliaria_caja;")


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0023_add_fecha_operacion_to_contrato'),
    ]

    operations = [
        migrations.RunPython(create_caja_table, reverse_code=drop_caja_table),
    ] 