# Generated by Django 4.2.7 on 2025-01-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0024_alquilermeses'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='tipo_cliente',
            field=models.CharField(choices=[('PARTICULAR', 'Particular'), ('EMPRESA', 'Empresa'), ('ESTUDIANTE', 'Estudiante')], default='PARTICULAR', max_length=20),
        ),
    ]
