# Generated by Django 4.2.7 on 2025-08-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0027_add_caja_id_to_movimientocaja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuotamensual',
            options={'ordering': ['contrato', 'numero_cuota'], 'unique_together': {('contrato', 'numero_cuota')}, 'verbose_name': 'Cuota Mensual', 'verbose_name_plural': 'Cuotas Mensuales'},
        ),
        migrations.AddField(
            model_name='contratoalquiler',
            name='operacion_principal',
            field=models.BooleanField(default=False, help_text='Indica si ya se realizó la operación principal (depósito + primer mes)'),
        ),
        migrations.AlterField(
            model_name='cuotamensual',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
