# Generated by Django 4.2.7 on 2025-02-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0028_conceptomovimiento_movimientocaja_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='caja',
            unique_together={('sucursal', 'estado')},
        ),
    ]
