# Generated by Django 4.2.7 on 2025-08-05 14:05

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0028_alter_cuotamensual_options_caja_id_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            # Eliminar la tabla actual
            "DROP TABLE IF EXISTS inmobiliaria_caja;",
            # No hay reverse SQL ya que la tabla se recreará
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            # Crear la tabla con la estructura correcta
            """
            CREATE TABLE inmobiliaria_caja (
                id BIGINT AUTO_INCREMENT PRIMARY KEY,
                numero INT UNSIGNED NOT NULL,
                sucursal_id BIGINT NOT NULL,
                fecha_apertura DATETIME(6) NOT NULL,
                fecha_cierre DATETIME(6) NULL,
                saldo_inicial DECIMAL(10,2) NOT NULL,
                saldo_final DECIMAL(10,2) NULL,
                estado VARCHAR(10) NOT NULL,
                usuario_apertura_id BIGINT NOT NULL,
                usuario_cierre_id BIGINT NULL,
                observaciones_apertura LONGTEXT NOT NULL,
                observaciones_cierre LONGTEXT NOT NULL,
                CONSTRAINT fk_caja_sucursal FOREIGN KEY (sucursal_id) REFERENCES inmobiliaria_sucursal (id),
                CONSTRAINT fk_caja_usuario_apertura FOREIGN KEY (usuario_apertura_id) REFERENCES auth_user (id),
                CONSTRAINT fk_caja_usuario_cierre FOREIGN KEY (usuario_cierre_id) REFERENCES auth_user (id),
                CONSTRAINT unique_numero_sucursal UNIQUE (numero, sucursal_id)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS inmobiliaria_caja;"
        ),
    ] 