# Generated by Django 4.2.7 on 2025-03-11 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0028_conceptomovimiento_movimientocaja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientocaja',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='referencia',
        ),
        migrations.AlterField(
            model_name='caja',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='inmobiliaria.sucursal'),
        ),
    ]
