# Generated by Django 4.2.7 on 2025-08-05 14:05

from django.db import migrations


def skip_on_postgresql(apps, schema_editor):
    """Esta tabla se crea con migraciones normales de Django"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0028_alter_cuotamensual_options_caja_id_and_more'),
    ]

    operations = [
        # Vaciado para PostgreSQL - las tablas se crean con migraciones normales de Django
        migrations.RunPython(skip_on_postgresql, reverse_code=migrations.RunPython.noop),
    ] 