# Generated by Django 4.2.7 on 2025-04-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0028_alter_historialdisponibilidad_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'ordering': ['-fecha_apertura']},
        ),
        migrations.AlterUniqueTogether(
            name='caja',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='caja',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='caja',
            table='inmobiliaria_caja',
        ),
    ]
