# Generated by Django 4.2.7 on 2025-08-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0029_alter_caja_table'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE inmobiliaria_caja
            MODIFY COLUMN numero INT UNSIGNED NOT NULL;
            """,
            reverse_sql="""
            ALTER TABLE inmobiliaria_caja
            MODIFY COLUMN numero INT UNSIGNED NOT NULL AUTO_INCREMENT;
            """
        ),
    ]
