# Generated by Django 4.2.7 on 2025-08-05 14:16

from django.db import migrations


def skip_on_postgresql(apps, schema_editor):
    """Esta modificación no es necesaria en PostgreSQL"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0029_alter_caja_table'),
    ]

    operations = [
        migrations.RunPython(skip_on_postgresql, reverse_code=migrations.RunPython.noop),
    ]
