# Generated by Django 4.2.7 on 2025-03-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0029_create_caja_models'),
    ]

    operations = [
    ]
