# Generated by Django 4.2.7 on 2025-08-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0030_caja_id_alter_caja_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoalquiler',
            name='fecha_cancelacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratoalquiler',
            name='motivo_cancelacion',
            field=models.TextField(blank=True),
        ),
    ]
