# Generated by Django 4.2.7 on 2025-03-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0030_initial_caja_setup'),
    ]

    operations = [
    ]
