# Generated by Django 4.2.7 on 2025-01-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0031_contratoalquiler_fecha_cancelacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoalquiler',
            name='dia_vencimiento',
            field=models.PositiveIntegerField(default=1, help_text='Día del mes para vencimiento de cuotas (1-28)'),
        ),
    ] 