# Generated by Django 4.2.7 on 2025-08-07 13:29

from django.db import migrations, models


def add_titulo_if_not_exists(apps, schema_editor):
    """Agregar campo titulo solo si no existe (compatibleMySQL/PostgreSQL)"""
    # En PostgreSQL, Django crea los campos automáticamente
    if schema_editor.connection.vendor == 'postgresql':
        return
    
    # Solo para MySQL
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'inmobiliaria_propiedad' 
            AND COLUMN_NAME = 'titulo'
        """)
        titulo_exists = cursor.fetchone()[0] > 0
        
        if not titulo_exists:
            cursor.execute("""
                ALTER TABLE inmobiliaria_propiedad 
                ADD COLUMN titulo varchar(255) NULL
            """)


def remove_titulo_field(apps, schema_editor):
    """Remover campo titulo"""
    with schema_editor.connection.cursor() as cursor:
        try:
            cursor.execute("ALTER TABLE inmobiliaria_propiedad DROP COLUMN titulo")
        except:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0032_add_dia_vencimiento_to_contrato'),
    ]

    operations = [
        migrations.RunPython(
            add_titulo_if_not_exists,
            remove_titulo_field,
        ),
        # REMOVIDO: AlterField que causaba conflicto con AUTO_INCREMENT
        # El manejo del campo 'numero' de Caja se hace en migración 0036
    ]
