# Generated by Django 4.2.7 on 2025-08-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0033_caja_id_propiedad_titulo_alter_caja_numero'),
    ]

    operations = [
    ]
