# Generated by Django 4.2.7 on 2025-08-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0035_add_fichado_por_to_propiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
