# Generated by Django 4.2.7 on 2025-08-08 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_all_missing_fields(apps, schema_editor):
    """Agregar campos que falten en propiedad - Solo para MySQL"""
    # En PostgreSQL, Django crea los campos automáticamente
    if schema_editor.connection.vendor == 'postgresql':
        return
    
    # Solo para MySQL
    with schema_editor.connection.cursor() as cursor:
        # Verificar titulo
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'inmobiliaria_propiedad' 
            AND COLUMN_NAME = 'titulo'
        """)
        titulo_exists = cursor.fetchone()[0] > 0
        
        # Verificar fichado_por_id
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'inmobiliaria_propiedad' 
            AND COLUMN_NAME = 'fichado_por_id'
        """)
        fichado_por_exists = cursor.fetchone()[0] > 0
        
        # Verificar fecha_fichado
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'inmobiliaria_propiedad' 
            AND COLUMN_NAME = 'fecha_fichado'
        """)
        fecha_fichado_exists = cursor.fetchone()[0] > 0
        
        # Agregar titulo si no existe
        if not titulo_exists:
            cursor.execute("""
                ALTER TABLE inmobiliaria_propiedad 
                ADD COLUMN titulo varchar(255) NULL
            """)
        
        # Agregar fichado_por_id si no existe
        if not fichado_por_exists:
            cursor.execute("""
                ALTER TABLE inmobiliaria_propiedad 
                ADD COLUMN fichado_por_id bigint NULL
            """)
            cursor.execute("""
                ALTER TABLE inmobiliaria_propiedad 
                ADD CONSTRAINT inmobiliaria_propiedad_fichado_por_id_fk 
                FOREIGN KEY (fichado_por_id) REFERENCES auth_user(id) ON DELETE SET NULL
            """)
        
        # Agregar fecha_fichado si no existe
        if not fecha_fichado_exists:
            cursor.execute("""
                ALTER TABLE inmobiliaria_propiedad 
                ADD COLUMN fecha_fichado datetime(6) NULL
            """)


def remove_all_fields(apps, schema_editor):
    """Remover campos agregados"""
    with schema_editor.connection.cursor() as cursor:
        try:
            cursor.execute("ALTER TABLE inmobiliaria_propiedad DROP COLUMN titulo")
        except:
            pass
        try:
            cursor.execute("ALTER TABLE inmobiliaria_propiedad DROP FOREIGN KEY inmobiliaria_propiedad_fichado_por_id_fk")
        except:
            pass
        try:
            cursor.execute("ALTER TABLE inmobiliaria_propiedad DROP COLUMN fichado_por_id")
        except:
            pass
        try:
            cursor.execute("ALTER TABLE inmobiliaria_propiedad DROP COLUMN fecha_fichado")
        except:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0036_caja_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            add_all_missing_fields,
            remove_all_fields,
        ),
    ]
