# Generated by Django 4.2.7 on 2025-09-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0038_create_recibo_model_clean'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialdisponibilidad',
            options={'ordering': ['fecha_inicio', 'fecha_fin'], 'verbose_name': 'Historial de Disponibilidad', 'verbose_name_plural': 'Historial de Disponibilidades'},
        ),
        migrations.AddField(
            model_name='caja',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(blank=True, help_text='Nombre o título para identificar fácilmente la propiedad', max_length=255, null=True, verbose_name='Título descriptivo'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='tipo_ins',
            field=models.CharField(blank=True, choices=[('csfl', 'CSFL'), ('exen', 'EXEN'), ('rins', 'RINS'), ('rnin', 'RNIN'), ('otro', 'Otro')], default='otro', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='tipo_ins',
            field=models.CharField(blank=True, choices=[('csfl', 'CSFL'), ('exen', 'EXEN'), ('rins', 'RINS'), ('rnin', 'RNIN'), ('otro', 'Otro')], default='otro', max_length=4, null=True),
        ),
    ]
