# Generated by Django 4.2.7 on 2025-09-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0039_alter_historialdisponibilidad_options_caja_id_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            # Permitir NULL en fecha_nacimiento para todas las tablas que heredan de Persona
            sql=[
                "ALTER TABLE inmobiliaria_inquilino MODIFY COLUMN fecha_nacimiento DATE NULL;",
                "ALTER TABLE inmobiliaria_propietario MODIFY COLUMN fecha_nacimiento DATE NULL;",
                "ALTER TABLE inmobiliaria_inquilino MODIFY COLUMN tipo_ins VARCHAR(4) NULL;",
                "ALTER TABLE inmobiliaria_propietario MODIFY COLUMN tipo_ins VARCHAR(4) NULL;",
            ],
            reverse_sql=[
                "ALTER TABLE inmobiliaria_inquilino MODIFY COLUMN fecha_nacimiento DATE NOT NULL;",
                "ALTER TABLE inmobiliaria_propietario MODIFY COLUMN fecha_nacimiento DATE NOT NULL;",
                "ALTER TABLE inmobiliaria_inquilino MODIFY COLUMN tipo_ins VARCHAR(4) NOT NULL;",
                "ALTER TABLE inmobiliaria_propietario MODIFY COLUMN tipo_ins VARCHAR(4) NOT NULL;",
            ]
        ),
    ]
