# Generated by Django 4.2.7 on 2025-09-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0040_auto_20250916_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'ordering': ['-fecha_apertura'], 'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
        migrations.AlterUniqueTogether(
            name='caja',
            unique_together={('numero', 'sucursal')},
        ),
    ]
