# Generated by Django 4.2.7 on 2025-09-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0041_alter_caja_options_alter_caja_unique_together'),
    ]

    operations = [
        migrations.RunSQL(
            # Permitir NULL en fecha_nacimiento y tipo_ins para Inquilino y Propietario
            sql=[
                "ALTER TABLE inmobiliaria_inquilino MODIFY COLUMN fecha_nacimiento DATE NULL;",
                "ALTER TABLE inmobiliaria_propietario MODIFY COLUMN fecha_nacimiento DATE NULL;",
                "ALTER TABLE inmobiliaria_inquilino MODIFY COLUMN tipo_ins VARCHAR(4) NULL;",
                "ALTER TABLE inmobiliaria_propietario MODIFY COLUMN tipo_ins VARCHAR(4) NULL;",
            ],
            reverse_sql=[
                "ALTER TABLE inmobiliaria_inquilino MODIFY COLUMN fecha_nacimiento DATE NOT NULL;",
                "ALTER TABLE inmobiliaria_propietario MODIFY COLUMN fecha_nacimiento DATE NOT NULL;",
                "ALTER TABLE inmobiliaria_inquilino MODIFY COLUMN tipo_ins VARCHAR(4) NOT NULL;",
                "ALTER TABLE inmobiliaria_propietario MODIFY COLUMN tipo_ins VARCHAR(4) NOT NULL;",
            ]
        ),
    ]
