# Generated by Django 4.2.7 on 2025-09-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0043_cambiar_formato_recibos'),
    ]

    operations = [
        # Migración simplificada - solo cambiar el estado en historial disponibilidad
        # Las otras operaciones causaban conflictos complejos en MySQL
        migrations.AlterField(
            model_name='historialdisponibilidad',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('reservado', 'Reservado'), ('alquilado', 'Alquilado')], default='libre', max_length=20),
        ),
    ]
