# Generated by Django 4.2.7 on 2025-09-19 13:56

from django.db import migrations, models, connection


def check_column_exists(table_name, column_name):
    """Verifica si una columna existe en una tabla"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = %s 
            AND COLUMN_NAME = %s
        """, [table_name, column_name])
        return cursor.fetchone()[0] > 0


def add_titulo_if_not_exists(apps, schema_editor):
    """Agrega el campo titulo solo si no existe"""
    if not check_column_exists('inmobiliaria_propiedad', 'titulo'):
        # Solo ejecutar si el campo no existe
        schema_editor.execute("""
            ALTER TABLE inmobiliaria_propiedad 
            ADD COLUMN titulo VARCHAR(255) NULL
        """)


def remove_titulo_if_exists(apps, schema_editor):
    """Remueve el campo titulo si existe"""
    if check_column_exists('inmobiliaria_propiedad', 'titulo'):
        schema_editor.execute("""
            ALTER TABLE inmobiliaria_propiedad 
            DROP COLUMN titulo
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0043_cambiar_formato_recibos'),
    ]

    operations = [
        # NOTA: Removimos la operación AddField para 'id' en 'caja' porque Django ya maneja este campo automáticamente
        # y estaba causando el error "can't have more than one auto-generated field"
        
        # Usar función personalizada para agregar titulo solo si no existe
        migrations.RunPython(add_titulo_if_not_exists, remove_titulo_if_exists),
        
        migrations.AlterField(
            model_name='caja',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='historialdisponibilidad',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('reservado', 'Reservado'), ('alquilado', 'Alquilado')], default='libre', max_length=20),
        ),
    ]
