# Generated by Django 4.2.7 on 2025-09-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0044_cambiar_estado_ocupado_a_alquilado'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='honorarios',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='sellados',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
