# Generated by Django 4.2.7 on 2025-09-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0046_add_honorarios_sellados_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratoalquiler',
            name='honorarios',
        ),
        migrations.RemoveField(
            model_name='contratoalquiler',
            name='sellados',
        ),
        migrations.AddField(
            model_name='caja',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(blank=True, help_text='Nombre o título para identificar fácilmente la propiedad', max_length=255, null=True, verbose_name='Título descriptivo'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
    ]
