# Generated by Django 4.2.7 on 2025-10-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0048_add_es_manual_to_disponibilidad'),
        ('inmobiliaria', '0050_add_anotaciones_to_propiedad'),
    ]

    operations = [
    ]
