# Generated by Django 4.2.7 on 2025-10-20 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0051_merge_20251006_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(blank=True, help_text='Nombre o título para identificar fácilmente la propiedad', max_length=255, null=True, verbose_name='Título descriptivo'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='historialdisponibilidad',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('reservado', 'Reservado'), ('alquilado', 'Operación')], default='libre', max_length=20),
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la cuenta (ej: Galicia, Mercado Pago, Banco Provincia)', max_length=100)),
                ('tipo', models.CharField(choices=[('banco', 'Banco'), ('billetera', 'Billetera Digital'), ('efectivo', 'Efectivo'), ('otro', 'Otro')], default='banco', max_length=20)),
                ('numero_cuenta', models.CharField(blank=True, help_text='Número de cuenta (opcional)', max_length=50, null=True)),
                ('cbu_alias', models.CharField(blank=True, help_text='CBU o Alias (opcional)', max_length=100, null=True)),
                ('activa', models.BooleanField(default=True, help_text='Si está activa aparecerá en los formularios de pago')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en los formularios')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='inmobiliaria.sucursal')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'ordering': ['sucursal', 'orden', 'nombre'],
                'unique_together': {('sucursal', 'nombre')},
            },
        ),
    ]
