# Generated by Django 4.2.7 on 2025-10-21 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0051_merge_20251006_1029'),
    ]

    operations = [
        # ✅ Removido AddField para caja.id porque ya existe
        migrations.AddField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(blank=True, help_text='Nombre o título para identificar fácilmente la propiedad', max_length=255, null=True, verbose_name='Título descriptivo'),
        ),
        migrations.AlterField(
            model_name='historialdisponibilidad',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('reservado', 'Reservado'), ('alquilado', 'Operación')], default='libre', max_length=20),
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_banco', models.CharField(help_text='Nombre del banco (ej: Banco Provincia)', max_length=100)),
                ('alias', models.CharField(blank=True, help_text='Alias de la cuenta (ej: GONNET-ALQUILERES)', max_length=100)),
                ('numero_cuenta', models.CharField(help_text='Número de cuenta bancaria', max_length=50)),
                ('tipo_cuenta', models.CharField(choices=[('banco', 'Banco'), ('billetera', 'Billetera Virtual')], default='banco', help_text='Tipo de cuenta', max_length=20)),
                ('activa', models.BooleanField(default=True, help_text='Si la cuenta está activa para usar')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='inmobiliaria.sucursal')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'ordering': ['nombre_banco', 'alias'],
            },
        ),
    ]
