# Generated by Django 4.2.7 on 2025-10-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0052_caja_id_propiedad_titulo_alter_caja_numero_and_more'),
    ]

    operations = [
        # ✅ Solo actualizar destino_deposito (otros campos ya existen en Heroku)
        migrations.AlterField(
            model_name='movimientocaja',
            name='destino_deposito',
            field=models.CharField(blank=True, choices=[('galicia', 'Galicia'), ('mp', 'Mercado Pago'), ('mixto', 'Mixto')], help_text="Puede ser 'galicia', 'mp', 'mixto', o 'cuenta_X' para cuentas bancarias dinámicas", max_length=50, null=True),
        ),
    ]
