# Generated by Django 4.2.7 on 2025-10-22 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0053_update_destino_deposito_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(blank=True, help_text='Nombre o título para identificar fácilmente la propiedad', max_length=255, null=True, verbose_name='Título descriptivo'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='historialdisponibilidad',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('reservado', 'Reservado'), ('alquilado', 'Operación')], default='libre', max_length=20),
        ),
        migrations.CreateModel(
            name='ComisionVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total_operacion', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total de la Operación')),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje de Comisión (%)')),
                ('monto_comision', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto de Comisión')),
                ('concepto_operacion', models.CharField(max_length=200, verbose_name='Concepto de la Operación')),
                ('fecha_operacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de la Operación')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cálculo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('movimiento_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_vendedor', to='inmobiliaria.movimientocaja', verbose_name='Movimiento de Caja')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_vendedor', to='inmobiliaria.reserva', verbose_name='Reserva')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Comisión de Vendedor',
                'verbose_name_plural': 'Comisiones de Vendedores',
                'ordering': ['-fecha_operacion'],
                'unique_together': {('vendedor', 'reserva', 'movimiento_caja')},
            },
        ),
    ]
