# Generated by Django 4.2.7 on 2025-10-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0054_caja_id_propiedad_titulo_alter_caja_numero_and_more'),
    ]

    operations = [
        # ✅ Migración vacía - Los campos ya existen en Heroku
        # Esta migración se mantiene para sincronización local
    ]
