# Generated by Django 4.2.7 on 2025-10-22 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0055_caja_id_propiedad_titulo_alter_caja_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValeVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto del Vale')),
                ('concepto', models.CharField(default='Vale', max_length=200, verbose_name='Concepto')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Vale')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('movimiento_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vales', to='inmobiliaria.movimientocaja', verbose_name='Movimiento de Caja')),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vales_otorgados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Otorgó el Vale')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vales', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Vale de Vendedor',
                'verbose_name_plural': 'Vales de Vendedores',
                'ordering': ['-fecha'],
            },
        ),
    ]
