# Generated by Django 4.2.7 on 2025-10-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0056_valevendedor'),
    ]

    operations = [
        # ✅ Solo actualizar el campo fecha de ValeVendedor
        migrations.AlterField(
            model_name='valevendedor',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha del Vale'),
        ),
    ]
