# Generated by Django 4.2.7 on 2025-10-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0056_valevendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(blank=True, help_text='Nombre o título para identificar fácilmente la propiedad', max_length=255, null=True, verbose_name='Título descriptivo'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='historialdisponibilidad',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('reservado', 'Reservado'), ('alquilado', 'Operación')], default='libre', max_length=20),
        ),
        migrations.AlterField(
            model_name='valevendedor',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha del Vale'),
        ),
    ]
