# Generated by Django 4.2.7 on 2025-10-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0057_caja_id_propiedad_titulo_alter_caja_numero_and_more'),
    ]

    operations = [
        # Solo agregar campos de asegurado a disponibilidad
        migrations.AddField(
            model_name='disponibilidad',
            name='asegurado',
            field=models.BooleanField(default=False, help_text='Indica si se realizó un pago adelantado', verbose_name='Asegurado'),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='moneda_asegurado',
            field=models.CharField(blank=True, choices=[('ARS', 'Pesos'), ('USD', 'Dólares')], default='ARS', max_length=10, null=True, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='monto_asegurado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto del pago adelantado', max_digits=12, null=True, verbose_name='Monto Asegurado'),
        ),
    ]
