# Generated by Django 4.2.7 on 2025-11-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0058_add_asegurado_fields_to_disponibilidad'),
    ]

    operations = [
        # ✅ Solo cambios de max_digits para permitir números más grandes
        migrations.AlterField(
            model_name='precio',
            name='precio_dia_toma',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Precio dia: Toma'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='precio_por_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Precio por día'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='precio_toma',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Precio Toma'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Precio total'),
        ),
    ]
