# Generated by Django 4.2.7 on 2025-11-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0059_aumentar_max_digits_precio'),
    ]

    operations = [
        # ✅ Solo agregar los nuevos tipos de precio: SEMANA_SANTA y CARNAVALES
        migrations.AlterField(
            model_name='precio',
            name='tipo_precio',
            field=models.CharField(choices=[('QUINCENA_1_DICIEMBRE', '1ra quincena Diciembre'), ('QUINCENA_2_DICIEMBRE', '2da quincena Diciembre'), ('QUINCENA_1_ENERO', '1ra quincena Enero'), ('QUINCENA_2_ENERO', '2da quincena Enero'), ('QUINCENA_1_FEBRERO', '1ra quincena Febrero'), ('QUINCENA_2_FEBRERO', '2da quincena Febrero'), ('QUINCENA_1_MARZO', '1ra quincena Marzo'), ('QUINCENA_2_MARZO', '2da quincena Marzo'), ('TEMPORADA_BAJA', 'Temporada baja'), ('VACACIONES_INVIERNO', 'Vacaciones Invierno'), ('FINDE_LARGO', 'Finde largo (5 noches)'), ('SEMANA_SANTA', 'Semana Santa (5 noches)'), ('CARNAVALES', 'Carnavales (5 noches)'), ('ESTUDIANTE', 'Estudiante')], max_length=20),
        ),
    ]
