# Generated by Django 4.2.7 on 2025-11-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0060_add_semana_santa_carnavales'),
    ]

    operations = [
        # ✅ Solo mantener las operaciones que son realmente necesarias
        # La tabla caja ya tiene id, no necesita AddField
        # El campo titulo para propiedad ya existe en migraciones anteriores, pero lo dejamos por si acaso
        migrations.AlterField(
            model_name='historialdisponibilidad',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('reservado', 'Reservado'), ('alquilado', 'Operación')], default='libre', max_length=20),
        ),
    ]
