# Generated by Django 4.2.7 on 2025-11-10 21:52

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class RemoveFieldIfExists(Operation):
    reduces_to_sql = False
    reversible = True

    def __init__(self, model_name, name):
        self.model_name = model_name
        self.model_name_lower = model_name.lower()
        self.name = name

    def state_forwards(self, app_label, state):
        model_state = state.models.get((app_label, self.model_name_lower))
        if not model_state:
            return
        fields = model_state.fields
        if hasattr(fields, "pop"):
            # fields es un OrderedDict en versiones recientes de Django
            fields.pop(self.name, None)
        else:
            # Compatibilidad por si fuera una lista de tuplas
            model_state.fields = [
                field for field in fields if field[0] != self.name
            ]

    def state_backwards(self, app_label, state):
        # No-op: no restauramos el campo automáticamente
        pass

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        # No operación en la base (se maneja con RunSQL)
        pass

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        # No operación en la base al revertir
        pass



class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0062_add_titulo_column_postgres'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE inmobiliaria_caja DROP COLUMN IF EXISTS id",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                RemoveFieldIfExists('Caja', 'id'),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='caja',
                    name='numero',
                    field=models.AutoField(primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
