# Generated by Django 4.2.7 on 2025-11-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0062_add_titulo_column_postgres'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE inmobiliaria_caja DROP COLUMN IF EXISTS id",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='caja',
                    name='id',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='caja',
                    name='numero',
                    field=models.AutoField(primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
