# Generated by Django 4.2.7 on 2025-11-25 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def verificar_y_agregar_titulo(apps, schema_editor):
    """Verifica si la columna titulo existe antes de agregarla"""
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'postgresql':
            # PostgreSQL: usar IF NOT EXISTS
            cursor.execute("""
                ALTER TABLE inmobiliaria_propiedad 
                ADD COLUMN IF NOT EXISTS titulo varchar(255) NULL
            """)
        elif vendor == 'mysql':
            # MySQL: verificar primero
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_schema = DATABASE()
                AND table_name='inmobiliaria_propiedad' 
                AND column_name='titulo'
            """)
            if not cursor.fetchone():
                cursor.execute("""
                    ALTER TABLE inmobiliaria_propiedad 
                    ADD COLUMN titulo VARCHAR(255) NULL
                """)


def verificar_y_agregar_campos_soft_delete(apps, schema_editor):
    """Verifica si los campos de soft delete existen antes de agregarlos"""
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'postgresql':
            # PostgreSQL: usar IF NOT EXISTS
            cursor.execute("""
                ALTER TABLE inmobiliaria_reserva 
                ADD COLUMN IF NOT EXISTS eliminada boolean NOT NULL DEFAULT FALSE
            """)
            cursor.execute("""
                ALTER TABLE inmobiliaria_reserva 
                ADD COLUMN IF NOT EXISTS fecha_eliminacion timestamp NULL
            """)
            cursor.execute("""
                ALTER TABLE inmobiliaria_reserva 
                ADD COLUMN IF NOT EXISTS usuario_eliminacion_id integer NULL
            """)
            
            # Verificar si la tabla auth_user existe antes de agregar foreign key constraint
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = 'auth_user'
                )
            """)
            auth_user_exists = cursor.fetchone()[0]
            
            if auth_user_exists:
                # Verificar si la constraint ya existe
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT FROM pg_constraint 
                        WHERE conname = 'inmobiliaria_reserva_usuario_eliminacion_id_fk'
                    )
                """)
                constraint_exists = cursor.fetchone()[0]
                
                if not constraint_exists:
                    # Agregar foreign key constraint solo si la tabla existe y la constraint no existe
                    cursor.execute("""
                        ALTER TABLE inmobiliaria_reserva 
                        ADD CONSTRAINT inmobiliaria_reserva_usuario_eliminacion_id_fk 
                        FOREIGN KEY (usuario_eliminacion_id) 
                        REFERENCES auth_user(id) 
                        ON DELETE SET NULL
                    """)
        
        elif vendor == 'mysql':
            # MySQL: verificar primero
            # Verificar campo eliminada
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_schema = DATABASE()
                AND table_name='inmobiliaria_reserva' 
                AND column_name='eliminada'
            """)
            if not cursor.fetchone():
                cursor.execute("""
                    ALTER TABLE inmobiliaria_reserva 
                    ADD COLUMN eliminada BOOLEAN NOT NULL DEFAULT FALSE
                """)
            
            # Verificar campo fecha_eliminacion
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_schema = DATABASE()
                AND table_name='inmobiliaria_reserva' 
                AND column_name='fecha_eliminacion'
            """)
            if not cursor.fetchone():
                cursor.execute("""
                    ALTER TABLE inmobiliaria_reserva 
                    ADD COLUMN fecha_eliminacion TIMESTAMP NULL
                """)
            
            # Verificar campo usuario_eliminacion_id
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_schema = DATABASE()
                AND table_name='inmobiliaria_reserva' 
                AND column_name='usuario_eliminacion_id'
            """)
            if not cursor.fetchone():
                cursor.execute("""
                    ALTER TABLE inmobiliaria_reserva 
                    ADD COLUMN usuario_eliminacion_id INTEGER NULL
                """)
                # Verificar si la tabla auth_user existe antes de agregar foreign key constraint
                cursor.execute("""
                    SELECT table_name 
                    FROM information_schema.tables 
                    WHERE table_schema = DATABASE()
                    AND table_name='auth_user'
                """)
                if cursor.fetchone():
                    # Verificar si la constraint ya existe
                    cursor.execute("""
                        SELECT constraint_name 
                        FROM information_schema.table_constraints 
                        WHERE table_schema = DATABASE()
                        AND table_name='inmobiliaria_reserva' 
                        AND constraint_name='inmobiliaria_reserva_usuario_eliminacion_id_fk'
                    """)
                    if not cursor.fetchone():
                        # Agregar foreign key constraint solo si la tabla existe y la constraint no existe
                        cursor.execute("""
                            ALTER TABLE inmobiliaria_reserva 
                            ADD CONSTRAINT inmobiliaria_reserva_usuario_eliminacion_id_fk 
                            FOREIGN KEY (usuario_eliminacion_id) 
                            REFERENCES auth_user(id) 
                            ON DELETE SET NULL
                        """)


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0063_remove_caja_id_alter_caja_numero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Agregar campo titulo solo si no existe
        migrations.RunPython(verificar_y_agregar_titulo, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='propiedad',
                    name='titulo',
                    field=models.CharField(blank=True, help_text='Nombre o título para identificar fácilmente la propiedad', max_length=255, null=True, verbose_name='Título descriptivo'),
                ),
            ]
        ),
        # Agregar campos de soft delete solo si no existen
        migrations.RunPython(verificar_y_agregar_campos_soft_delete, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='reserva',
                    name='eliminada',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='reserva',
                    name='fecha_eliminacion',
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='reserva',
                    name='usuario_eliminacion',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_eliminadas', to=settings.AUTH_USER_MODEL),
                ),
            ]
        ),
    ]
