# Generated by Django 4.2.7 on 2025-11-19 17:25

from django.db import migrations, models


def verificar_y_agregar_titulo(apps, schema_editor):
    """
    Verifica si la columna titulo ya existe antes de intentar crearla.
    Si ya existe, no hace nada.
    """
    with schema_editor.connection.cursor() as cursor:
        # Verificar si la columna ya existe
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='inmobiliaria_propiedad' 
            AND column_name='titulo'
        """)
        existe = cursor.fetchone()
        
        if not existe:
            # Si no existe, agregarla
            cursor.execute("""
                ALTER TABLE inmobiliaria_propiedad 
                ADD COLUMN titulo VARCHAR(255) NULL
            """)


def revertir_titulo(apps, schema_editor):
    """
    Función de reversión (opcional)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0063_remove_caja_id_alter_caja_numero'),
    ]

    operations = [
        # Primero verificar y agregar la columna en la BD si no existe
        migrations.RunPython(verificar_y_agregar_titulo, revertir_titulo),
        # Luego agregar el campo al estado de Django (sin tocar la BD)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='propiedad',
                    name='titulo',
                    field=models.CharField(blank=True, help_text='Nombre o título para identificar fácilmente la propiedad', max_length=255, null=True, verbose_name='Título descriptivo'),
                ),
            ],
        ),
    ]
