# Generated by Django 4.2.7 on 2025-11-25 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0063_remove_caja_id_alter_caja_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(blank=True, help_text='Nombre o título para identificar fácilmente la propiedad', max_length=255, null=True, verbose_name='Título descriptivo'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='eliminada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario_eliminacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_eliminadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
