# Generated by Django 4.2.7 on 2025-11-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0064_agregar_soft_delete_reservas'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='camas',
            field=models.CharField(blank=True, help_text='Descripción de las camas (ej: 1 cama matrimonial, 2 camas individuales, etc.)', max_length=255, null=True, verbose_name='Camas'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='cantidad_personas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de personas'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='numero_por_propietario',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de propiedad'),
        ),
    ]
