# Generated by Django 4.2.7 on 2025-11-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0064_agregar_soft_delete_reservas'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='camas',
            field=models.CharField(blank=True, help_text='Descripción de las camas (ej: 1 cama matrimonial, 2 camas individuales, etc.)', max_length=255, null=True, verbose_name='Camas'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='cantidad_personas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de personas'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='numero_por_propietario',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de propiedad'),
        ),
        # Eliminar el constraint único antiguo y crear uno nuevo con condición
        migrations.RunSQL(
            # Para PostgreSQL: eliminar constraint y crear uno parcial
            sql=[
                "ALTER TABLE inmobiliaria_propiedad DROP CONSTRAINT IF EXISTS unique_num_x_prop;",
                "CREATE UNIQUE INDEX unique_num_x_prop ON inmobiliaria_propiedad (propietario_id, numero_por_propietario) WHERE numero_por_propietario IS NOT NULL;"
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS unique_num_x_prop;",
                "ALTER TABLE inmobiliaria_propiedad ADD CONSTRAINT unique_num_x_prop UNIQUE (propietario_id, numero_por_propietario);"
            ],
            # Para MySQL: usar un enfoque diferente
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='propiedad',
                    name='unique_num_x_prop',
                ),
            ]
        ),
    ]
