# Generated by Django 4.2.7 on 2025-11-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0064_agregar_soft_delete_reservas'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='camas',
            field=models.CharField(blank=True, help_text='Descripción de las camas (ej: 1 cama matrimonial, 2 camas individuales, etc.)', max_length=255, null=True, verbose_name='Camas'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='cantidad_personas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de personas'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='numero_por_propietario',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de propiedad'),
        ),
        # Eliminar el constraint único antiguo y crear uno nuevo con condición
        migrations.RunSQL(
            # Eliminar constraint antiguo si existe
            sql="ALTER TABLE inmobiliaria_propiedad DROP INDEX IF EXISTS unique_num_x_prop;",
            reverse_sql="ALTER TABLE inmobiliaria_propiedad ADD CONSTRAINT unique_num_x_prop UNIQUE (propietario_id, numero_por_propietario);"
        ),
        migrations.AddConstraint(
            model_name='propiedad',
            constraint=models.UniqueConstraint(
                fields=['propietario', 'numero_por_propietario'],
                name='unique_num_x_prop',
                condition=models.Q(numero_por_propietario__isnull=False)
            ),
        ),
    ]
