# Generated by Django 4.2.7 on 2025-12-09 17:31

from django.db import migrations, models
import inmobiliaria.models.persona


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0065_agregar_cantidad_personas_camas_y_numero_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='directv_prepago',
            field=models.BooleanField(default=False, verbose_name='DirecTV prepago'),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[inmobiliaria.models.persona.validate_dni]),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[inmobiliaria.models.persona.validate_dni]),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
