# Generated by Django 4.2.7 on 2025-12-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0066_agregar_directv_prepago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquilino',
            name='tipo_doc',
            field=models.CharField(choices=[('dni', 'DNI'), ('cuit', 'CUIT'), ('le', 'LE'), ('ls', 'LS'), ('cipf', 'CIPF'), ('pas', 'PAS')], default='otro', max_length=4),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='tipo_doc',
            field=models.CharField(choices=[('dni', 'DNI'), ('cuit', 'CUIT'), ('le', 'LE'), ('ls', 'LS'), ('cipf', 'CIPF'), ('pas', 'PAS')], default='otro', max_length=4),
        ),
    ]
