# Generated by Django 4.2.7 on 2025-12-15 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0067_agregar_cuit_tipo_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlquilerInvierno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(default=False, verbose_name='Disponible para alquiler invierno')),
                ('precio_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio mensual')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('ocupado', 'Ocupado')], default='disponible', max_length=20, verbose_name='Estado del alquiler')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('precio_expensas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de expensas')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('propiedad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_invierno', to='inmobiliaria.propiedad')),
            ],
            options={
                'verbose_name': 'Alquiler Invierno',
                'verbose_name_plural': 'Alquileres Invierno',
            },
        ),
    ]
