# Generated by Django 4.2.7 on 2025-12-17 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0068_add_alquiler_invierno'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionPropietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total_operacion', models.DecimalField(decimal_places=2, help_text='Monto total recibido del inquilino', max_digits=12, verbose_name='Monto Total de la Operación')),
                ('monto_propietario', models.DecimalField(decimal_places=2, help_text='Monto que corresponde pagar al propietario', max_digits=12, verbose_name='Monto para el Propietario')),
                ('monto_inmobiliaria', models.DecimalField(decimal_places=2, help_text='Monto que corresponde a la inmobiliaria (comisión)', max_digits=12, verbose_name='Monto para la Inmobiliaria')),
                ('monto_gastos', models.DecimalField(decimal_places=2, default=0, help_text='Suma de gastos aceptados del propietario', max_digits=12, verbose_name='Total de Gastos')),
                ('monto_a_pagar', models.DecimalField(decimal_places=2, help_text='Monto final a pagar al propietario (monto_propietario - gastos)', max_digits=12, verbose_name='Monto a Pagar')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesada', 'Procesada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('fecha_desde', models.DateField(blank=True, help_text='Fecha de inicio del período liquidado', null=True, verbose_name='Fecha Desde')),
                ('fecha_hasta', models.DateField(blank=True, help_text='Fecha de fin del período liquidado', null=True, verbose_name='Fecha Hasta')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones', to='inmobiliaria.contratoalquiler', verbose_name='Contrato')),
                ('movimiento_caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones', to='inmobiliaria.movimientocaja', verbose_name='Movimiento de Caja')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='inmobiliaria.propiedad', verbose_name='Propiedad')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='inmobiliaria.propietario', verbose_name='Propietario')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones', to='inmobiliaria.reserva', verbose_name='Reserva')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='inmobiliaria.sucursal', verbose_name='Sucursal')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó la liquidación')),
            ],
            options={
                'verbose_name': 'Liquidación Propietario',
                'verbose_name_plural': 'Liquidaciones Propietarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='GastoPropietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción del gasto (ej: Luz, Gas, Mantenimiento)', max_length=200, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('fecha_gasto', models.DateField(blank=True, null=True, verbose_name='Fecha del Gasto')),
                ('aceptado', models.BooleanField(default=False, help_text='Si está aceptado, se descuenta del monto a pagar', verbose_name='Aceptado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='inmobiliaria.liquidacionpropietario', verbose_name='Liquidación')),
            ],
            options={
                'verbose_name': 'Gasto Propietario',
                'verbose_name_plural': 'Gastos Propietarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
