# Generated by Django 4.2.7 on 2025-12-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0069_liquidacionpropietario_gastopropietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='porcentaje_propietario',
            field=models.DecimalField(blank=True, decimal_places=2, default=85.0, help_text='Porcentaje del monto total que corresponde al propietario (ej: 85% = 85.00). El resto es para la inmobiliaria.', max_digits=5, null=True, verbose_name='Porcentaje para Propietario (%)'),
        ),
    ]
