# Generated by Django 4.2.7 on 2025-12-17 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0070_propiedad_porcentaje_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastopropietario',
            name='propiedad',
            field=models.ForeignKey(blank=True, help_text='Propiedad relacionada con el gasto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos_pendientes', to='inmobiliaria.propiedad', verbose_name='Propiedad'),
        ),
        migrations.AddField(
            model_name='gastopropietario',
            name='propietario',
            field=models.ForeignKey(blank=True, help_text='Propietario al que pertenece el gasto (si no hay liquidación)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos_pendientes', to='inmobiliaria.propietario', verbose_name='Propietario'),
        ),
        migrations.AddField(
            model_name='gastopropietario',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos_propietario', to='inmobiliaria.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='gastopropietario',
            name='liquidacion',
            field=models.ForeignKey(blank=True, help_text='Si está vacío, es un gasto pendiente del propietario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='inmobiliaria.liquidacionpropietario', verbose_name='Liquidación'),
        ),
    ]
