# Generated by Django 4.2.7 on 2025-12-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0071_gastopropietario_propiedad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='aire',
            field=models.BooleanField(default=False, verbose_name='Aire acondicionado'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='cable',
            field=models.BooleanField(default=False, verbose_name='Cable'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='ventilador',
            field=models.BooleanField(default=False, verbose_name='Ventilador'),
        ),
    ]
