# Generated by Django 4.2.7 on 2026-04-23 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0107_vendedor_comision_por_dia_etiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisionvendedor',
            name='rol_comision',
            field=models.CharField(default='general', help_text='Permite varias líneas por movimiento (fichaje, operación día/invierno/24 meses).', max_length=32, verbose_name='Rol de comisión'),
        ),
        migrations.AlterField(
            model_name='contratoalquiler',
            name='inquilino',
            field=models.ForeignKey(help_text='Inquilino principal (el primero si hay varios)', on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='inmobiliaria.inquilino'),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='liquidacionpropietario',
            name='monto_a_pagar',
            field=models.DecimalField(decimal_places=2, help_text='Monto final a pagar al propietario (monto_propietario − gastos − fondo de mantenimiento)', max_digits=12, verbose_name='Monto a Pagar'),
        ),
        migrations.AlterField(
            model_name='mescomisionpagadovendedor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='a_descontar',
            field=models.CharField(blank=True, choices=[('propietario', 'Propietario'), ('oficina', 'Oficina'), ('inquilino', 'Inquilino')], help_text='Solo necesario para egresos', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo_inmueble',
            field=models.CharField(choices=[('campo', 'Campo'), ('casa-chalet', 'Casa - Chalet'), ('departamento', 'Departamento'), ('fondo_de_comercio', 'Fondo de Comercio'), ('galpon', 'Galpón'), ('hotel', 'Hotel'), ('local', 'Local'), ('oficina', 'Oficina'), ('ph', 'PH'), ('quinta', 'Quinta'), ('terreno', 'Terreno'), ('lote', 'Lote'), ('cochera', 'Cochera'), ('edificio', 'Edificio'), ('inmueble_en_block', 'Inmueble en Block'), ('duplex', 'Dúplex'), ('emprendimiento', 'Emprendimiento'), ('cabaña', 'Cabaña'), ('casaquinta', 'Casa Quinta'), ('deposito', 'Depósito')], default='departamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='cheques',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registro',
            name='deposito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registro',
            name='efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registro',
            name='liquidacion',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registro',
            name='qr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tarjeta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='valevendedor',
            name='tipo_vale',
            field=models.CharField(choices=[('IN', 'Ingreso'), ('EG', 'Egreso')], default='EG', help_text='EG: dinero que sale de caja hacia el productor. IN: dinero que ingresa a caja desde el productor.', max_length=2, verbose_name='Tipo de vale'),
        ),
    ]
